name: PR Pipeline

on:
  pull_request:

jobs:
  linting:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22.9.0
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install --with dev
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
